name: Publish Python Package to TestPyPI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update version in files
        run: |
          sed -i "s/^version = .*/version = $VERSION/" setup.cfg
          sed -i "s/^__version__ = .*/__version__ = \"$VERSION\"/" example_pkg/__init__.py

      - name: Build package
        run: python -m build
      
      - name: Check package validity
        run: twine check dist/*

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          trust-publisher: true

      - name: Commit updated version files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout main
          git pull origin main
          git add setup.cfg example_pkg/__init__.py
          git commit -m "Update version to $VERSION"
          git push origin main
